default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: winter-party
  password: satoru0021
  timeout: 5000

development:
  <<: *default
  database: winter-party_development

test:
  <<: *default
  database: winter-party_test

production:
  <<: *default
  database: bundler_production
  username: satoru
  password: satoru0021
